flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-ios-obs-manager-x1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#0A1D29" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/icon-ios-obs-manager-x1.png" # For adaptive icons on Android
  windows:
    generate: true
    image_path: "assets/icon-ios-obs-manager-x1.png"
    icon_size: 48 # min:48, max:256, default: 48