name: obs_for_sama
description: "A new Flutter project to manage OBS."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.19.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  app_with_flutter_bloc:
    path: packages/app_with_flutter_bloc
  app_with_get_x:
    path: packages/app_with_get_x

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:

  uses-material-design: true
#  fonts:
#    - family: UnicaOne
#      fonts:
#        - asset: fonts/unica_one/UnicaOne-Regular.ttf
#          weight: 600
#    - family: Roboto
#      fonts:
#        - asset: fonts/roboto/Roboto-VariableFont_wdth,wght.ttf
#        - asset: fonts/roboto/Roboto_Condensed-SemiBold.ttf
#          weight: 700
#  assets:
#    - assets/
