name: app_with_flutter_bloc
description: "A new Flutter project to manage OBS."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.18.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.1

  # Fonts
  google_fonts: ^6.2.1 # Installer les fichiers c'est mieux

  # Package metier
  obs_websocket: ^5.2.3
  mobile_scanner: ^7.0.1

  # Package metier - Pour empecher la mise en veille de l'app
  wakelock_plus: ^1.3.2

  # Cache
  shared_preferences: ^2.5.3

  # State manager
  get: ^4.6.6 # A remplacer
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Models
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  json_serializable: ^6.11.0
  json_annotation: ^4.9.0

  # Pour windows (demande spécial)
  bitsdojo_window: ^0.1.6

  # Logo and splash_master
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  dartz: ^0.10.1

  # Connectivity (wifi, bluetooth ect...)
  connectivity_plus: ^6.1.5

  # Version info
  package_info_plus: ^8.3.1

  # Responsive design
  sizer: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Builder
  build_runner: ^2.6.0

  # Linter
  very_good_analysis: ^9.0.0
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: UnicaOne
      fonts:
        - asset: fonts/unica_one/UnicaOne-Regular.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-VariableFont_wdth,wght.ttf
        - asset: fonts/roboto/Roboto_Condensed-SemiBold.ttf
          weight: 700
  assets:
    - assets/
