on:
  push:
    branches:
      - main

name: 📎 [MERGE] Create an apk android file on merge to main branch.
jobs:
  create-tags:
    #    runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
      - run: echo "🎉 Good 🎉. The job is starting on event ${{ github.event_name }}."
      - run: echo "The name of the branch is ${{ github.ref }} et the name of the repository is ${{ github.repository }}."

      - uses: actions/checkout@v3

      - name: Get version from pubspec.yaml
        id: version
        run: |
          $version = (Get-Content pubspec.yaml | Select-String 'version:[^^]*' | ForEach-Object { $_.ToString().Split(":")[1].Trim() })
          echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Use the value
        run: |
          echo "${{ env.APP_VERSION }}"

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Installation de Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          architecture: x64
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter pub get
          flutter build apk

      - name: Create a GitHub release
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/obs-manager-${{ env.APP_VERSION }}.apk
